CLASS zcl_68_billing_dep_lgl_c367_cv DEFINITION INHERITING FROM zcl_67_observer_lgl_c367_cv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA state TYPE string.
    METHODS: on_modified_state REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_68_BILLING_DEP_LGL_C367_CV IMPLEMENTATION.


  METHOD on_modified_state.
    me->state = ev_new_state.
  ENDMETHOD.
ENDCLASS.
