CLASS zcl_amdp_tf_c367_01_cv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES: if_amdp_marker_hdb.

*    CLASS-METHODS: get_cust_bookings FOR TABLE FUNCTION ZTF_01_LOG_C367_CV.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_AMDP_TF_C367_01_CV IMPLEMENTATION.
ENDCLASS.
