CLASS zcx_52_exception2_lgl_c367_cv DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_52_exception2_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
